### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by wandersonmaracaipe** [isaqueribeiro/sge#3]
Olá. Encontrei o seu repositório e gostaria de contribuir de alguma forma porém estou com dificuldades para compilar e perceber a estrutura do projeto. Poderia por gentileza sanar algumas dúvidas? Segue meu contato WhatsApp: +55 63 98120-6827.

Hello... I found your repository and would like to contribute in some way but I am having difficulties to compile and understand the structure of the project. Could you please resolve some doubts? Follow my WhatsApp contact: +55 63 98120-6827.

**Comment by isaqueribeiro** [comment]
Perdão, Wanderson!
Pensei que já tinha te respondido.... estou disposto a ajudar caso ainda estej interessado.

+ 55 91 991460-0444
isaque.ribeiro@outlook.com
